#-------------------------------
# General Site Settings

menu:
- {name: 'Research', url: 'pages/research.html'}
- {name: 'Updates', url: 'pages/news.html'}
#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Samson Koelle'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section


contact: >
  # Contact

  You may contact me [through my email](mailto:sjkoelle(at)gmail{dot}com) or [tweet at me](https://twitter.com/seattlestatsam) .

#-------------------------------
# Work Section

projects:
- {name: 'Interpreting Learned Representations', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Single-cell RNA-sequencing', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Genetic Engineering and Stem Cell Tracking', folder: 'proj-3', file: 'projects/proj-3.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
